[package]
name = "kilo_in_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.1"
rustix = { version = "0.36.5", features = ["termios"] }
scanf = "1.2.1"